<head>
    <meta charset="UTF-8">
    <meta name="author" content="lianghguaquanqiu FE Team"/>
    <meta name="Description" content="量·财富"/>
    <meta name="Keywords" content="量·财富"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no"/>
    <title>量·财富</title>
    <link rel="stylesheet" href="../css/style.min.css"/>
</head>
